### ISSUE TITLE
Update ReadMe on the project status? 

### ISSUE THREAD

**Issue by GiriB** [stuartbarr/azure-key-vault#1]
Hey, it looks like this is not maintained anymore? Can we update the ReadMe with whatever plans/recommendation/status for the author to the community? 

P.S - I see [this fork](https://github.com/MikeAScott/azure-key-vault) has more recent developments. I think it helps the community if we have project status in the ReadMe so contributors can take a better call on where to contribute. 

Thanks!

**Comment by stuartbarr** [comment]
Updated README to no longer maintained.
